name: Build and Deploy (DEV Only)

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    container:
      image: node:22
      options: --memory=4096m
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: us-east-1

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install AWS CLI
        run: |
          apt-get update && apt-get install -y unzip curl
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          ./aws/install

      - name: Set DEV environment vars
        run: |
          echo "Using DEV environment"
          echo "S3_BUCKET=happyhour-dev-bucket" >> $GITHUB_ENV
          echo "CF_DIST_ID=E1UBYQQZBOFPK4" >> $GITHUB_ENV
          echo "ENVIRONMENT=dev" >> $GITHUB_ENV
          echo "S3_ENV_PATH=s3://happyhour-env-bucket/fe-dev-env/env" >> $GITHUB_ENV

      - name: Download environment file from S3
        run: |
          aws s3 cp ${{ env.S3_ENV_PATH }} .
          mv env .env

      - name: Remove package-lock.json and node_modules and dist
        run: |
          rm -f package-lock.json
          rm -rf node_modules
          rm -rf dist

      - name: Install Node dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Verify files to deploy
        run: ls -la dist/

      - name: Upload to S3
        run: |
          echo "Uploading files to $S3_BUCKET"
          aws s3 cp dist/ s3://$S3_BUCKET/ --recursive

      - name: Invalidate CloudFront cache
        run: |
          echo "Invalidating CloudFront distribution $CF_DIST_ID"
          aws cloudfront create-invalidation --distribution-id $CF_DIST_ID --paths "/*"
